name: Test API with Bruno

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Clone Bruno CLI from GitHub
        run: git clone https://github.com/usebruno/bruno.git

      - name: Install Bruno dependencies
        run: |
          cd bruno
          npm install
          npm run build

      - name: Run Bruno tests
        run: |
          ./bin/bru run ../bruno-tests/ \
          --reporters cli,json \
          --reporter-json-export ../test-reports/bruno-report.json
