name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

     
      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Install GPG
        run: sudo apt-get install gnupg

      - name: Import GPG Private Key
        run: |
          echo "${{ secrets.GPG_KEYS }}" | gpg --batch --no-use-agent --import

      - name: Sign the Jar File
        run: |
          gpg --batch --yes --passphrase "${{ secrets.PASSPHRASE }}" --pinentry-mode loopback \
          --output bootstrap/build/libs/bootstrap-signed.jar --sign bootstrap/build/libs/bootstrap.jar
          
      - name: Upload Signed JAR Artifact
        uses: actions/upload-artifact@v2
        with:
          name: signed-jar
          path: bootstrap/build/libs/bootstrap-signed.jar
          
      - name: Run Unit Tests
        run: ./gradlew test --stacktrace
        
      - name: Start the Java application
        run: |
           nohup java -jar bootstrap/build/libs/bootstrap.jar &
          
      - name: Wait for the application to start
        run: |
          echo "Waiting for the application to start..."
          sleep 20 
          
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli 

      - name: Run Bruno tests
        run: |
          cd bruno-tests
          bru run --env local
          
    
